- type: job
  id: BDWPlatoonLeader
  name: job-name-BDW-platoonleader
  description: job-description-BDW-platoonleader
  playTimeTracker: BDWPlatoonLeader
  startingGear: BDWUniformPlatoonLeader
  icon: "Nato"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 10
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWTeamLeader
  name: job-name-BDW-teamleader
  description: job-description-BDW-teamleader
  playTimeTracker: BDWTeamLeader
  startingGear: BDWUniformTeamLeader
  icon: "Nato"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 9
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWMachineGunner
  name: job-name-BDW-machinegunner
  description: job-description-BDW-machinegunner
  playTimeTracker: BDWMachineGunner
  startingGear: BDWUniformMachineGunner
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 6
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWMedic
  name: job-name-BDW-medic
  description: job-description-BDW-medic
  playTimeTracker: BDWMedic
  startingGear: BDWUniformMedic
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 7
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWSniper
  name: job-name-BDW-sniper
  description: job-description-BDW-sniper
  playTimeTracker: BDWSniper
  startingGear: BDWUniformSniper
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 5
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWRTO
  name: job-name-BDW-rto
  description: job-description-BDW-rto
  playTimeTracker: BDWRTO
  startingGear: BDWUniformRTO
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 8
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: job
  id: BDWRifleMan
  name: job-name-BDW-rifleman
  description: job-description-BDW-rifleman
  playTimeTracker: BDWRifleMan
  startingGear: BDWUniformRifleMan
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 4
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "Bundeswehr"

- type: playTimeTracker
  id: BDWPlatoonLeader

- type: playTimeTracker
  id: BDWTeamLeader

- type: playTimeTracker
  id: BDWMachineGunner

- type: playTimeTracker
  id: BDWMedic

- type: playTimeTracker
  id: BDWSniper

- type: playTimeTracker
  id: BDWRTO

- type: playTimeTracker
  id: BDWRifleMan

- type: startingGear
  id: BDWUniformPlatoonLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWGrenadeFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHatBeretBDW
    eyes: ClothingEyesGlassesCheapSunglasses
    pocket1: IFAKBDWFilled

- type: startingGear
  id: BDWUniformTeamLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWGrenadeFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHatBeretBDW
    pocket1: IFAKBDWFilled

- type: startingGear
  id: BDWUniformMachineGunner
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackAliceMediumFilledMachineGunnerBDW
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWAmmoLMGFilled
    pouchright: FHClothingPouchBDWAmmoLMGFilled
    suitstorage: FHWeaponLMGMG3
    head: FHClothingHeadHelmetM62
    pocket1: IFAKBDWFilled

- type: startingGear
  id: BDWUniformMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackBDWButtPackMedic
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWAmmoFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHelmetM62Medic
    pocket1: IFAKBDWFilled
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesLatex

- type: startingGear
  id: BDWUniformSniper
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackBDWButtPack
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWAmmoFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHelmetM62
    pocket1: IFAKBDWFilled

- type: startingGear
  id: BDWUniformRTO
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWAmmoFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHelmetM62
    pocket1: IFAKBDWFilled

- type: startingGear
  id: BDWUniformRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitBDWGray
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackBDWButtPack
    belt: FHClothingBeltBDWHarness
    pouchleft: FHClothingPouchBDWAmmoFilled
    pouchright: FHClothingPouchBDWAmmoFilled
    suitstorage: FHWeaponRifleG3A3
    head: FHClothingHeadHelmetM62
    pocket1: IFAKBDWFilled
