- type: department
  id: USMC
  name: department-USMC
  description: department-USMC-description
  color: "#4168DB"
  roles:
  - USMCPlatoonLeader
  - USMCTeamLeader
  - USMCMachineGunner
  - USMCMedic
  - USMCSniper
  - USMCRTO
  - USMCRifleMan

- type: department
  id: USSR
  name: department-USSR
  description: department-USSR-description
  color: "#B5201B"
  roles:
  - USSRPlatoonLeader
  - USSRTeamLeader
  - USSRMachineGunner
  - USSRMedic
  - USSRSniper
  - USSRAutoRifleMan
  - USSRRTO
  - USSRRifleMan
