- type: department
  id: USMC
  name: department-USMC
  description: department-USMC-description
  color: "#4168DB"
  roles:
  - USMCPlatoonLeader
  - USMCTeamLeader
  - USMCMachineGunner
  - USMCMedic
  - USMCSniper
  - USMCRTO
  - USMCRifleMan

- type: department
  id: USSR
  name: department-USSR
  description: department-USSR-description
  color: "#B5201B"
  roles:
  - USSRPlatoonLeader
  - USSRTeamLeader
  - USSRMachineGunner
  - USSRMedic
  - USSRSniper
  - USSRAutoRifleMan
  - USSRRTO
  - USSRRifleMan

- type: department
  id: BDW
  name: department-BDW
  description: department-BDW-description
  color: "#4168DB"
  roles:
  - BDWPlatoonLeader
  - BDWTeamLeader
  - BDWMachineGunner
  - BDWMedic
  - BDWSniper
  - BDWRTO
  - BDWRifleMan

- type: department
  id: NVA
  name: department-NVA
  description: department-NVA-description
  color: "#4168DB"
  roles:
  - NVAPlatoonLeader
  - NVATeamLeader
  - NVAMachineGunner
  - NVAMedic
  - NVASniper
  - NVAAutoRifleMan
  - NVARTO
  - NVARifleMan
