- type: job
  id: USMCTeamLeader
  name: job-name-USMC-teamleader
  description: job-description-USMC-teamleader
  playTimeTracker: USMCTeamLeader
  startingGear: USMCSleepingUniform
  icon: "USMC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: job
  id: USMCRifleMan
  name: job-name-USMC-rifleman
  description: job-description-USMC-rifleman
  playTimeTracker: USMCRifleMan
  startingGear: USMCSleepingUniform
  icon: "USMC"
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: startingGear
  id: USMCSleepingUniform
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack

- type: playTimeTracker
  id: USMCTeamLeader

- type: playTimeTracker
  id: USMCRifleMan

- type: jobIcon
  parent: JobIcon
  id: USMC
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: NATO
  jobName: job-name-USMC-rifleman
  isCrewJob: false
