- type: job
  id: USMCPlatoonLeader
  name: job-name-USMC-platoonleader
  description: job-description-USMC-platoonleader
  playTimeTracker: USMCPlatoonLeader
  startingGear: USMCSleepingUniform
  icon: "USMCPlatoonLeader"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: job
  id: USMCTeamLeader
  name: job-name-USMC-teamleader
  description: job-description-USMC-teamleader
  playTimeTracker: USMCTeamLeader
  startingGear: USMCSleepingUniform
  icon: "USMCTeamLeader"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: job
  id: USMCMachineGunner
  name: job-name-USMC-machinegunner
  description: job-description-USMC-machinegunner
  playTimeTracker: USMCMachineGunner
  startingGear: USMCSleepingUniform
  icon: "USMCMachineGunner"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: job
  id: USMCMedic
  name: job-name-USMC-medic
  description: job-description-USMC-medic
  playTimeTracker: USMCMedic
  startingGear: USMCSleepingUniform
  icon: "USMCMedic"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: job
  id: USMCRifleMan
  name: job-name-USMC-rifleman
  description: job-description-USMC-rifleman
  playTimeTracker: USMCRifleMan
  startingGear: USMCSleepingUniform
  icon: "USMCRifleMan"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer

- type: startingGear
  id: USMCSleepingUniform
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack

- type: playTimeTracker
  id: USMCPlatoonLeader

- type: playTimeTracker
  id: USMCTeamLeader

- type: playTimeTracker
  id: USMCMachineGunner

- type: playTimeTracker
  id: USMCMedic

- type: playTimeTracker
  id: USMCRifleMan

- type: jobIcon
  parent: JobIcon
  id: USMCPlatoonLeader
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: nato_platoonleader
  jobName: job-name-USMC-platoonleader
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USMCTeamLeader
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: nato_teamleader
  jobName: job-name-USMC-teamleader
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USMCMachineGunner
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: nato_machinegunner
  jobName: job-name-USMC-machinegunner
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USMCMedic
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: nato_medic
  jobName: job-name-USMC-medic
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USMCRifleMan
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: nato_rifleman
  jobName: job-name-USMC-rifleman
  isCrewJob: false
