- type: job
  id: USMCPlatoonLeader
  name: job-name-USMC-platoonleader
  description: job-description-USMC-platoonleader
  playTimeTracker: USMCPlatoonLeader
  startingGear: USMCUniformPlatoonLeader
  icon: "Nato"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 10
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCPlatoonLeader

- type: startingGear
  id: USMCUniformPlatoonLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmorPASGT
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCGrenadeFilled
    pouchright: FHClothingPouchUSMCAmmoDoubleFilled
    suitstorage: FHWeaponRifleM16A1
    head: FHClothingHeadHatBeretUSMC
    pocket1: IFAKUSMCFilled

- type: job
  id: USMCTeamLeader
  name: job-name-USMC-teamleader
  description: job-description-USMC-teamleader
  playTimeTracker: USMCTeamLeader
  startingGear: USMCUniformTeamLeader
  icon: "Nato"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 9
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCTeamLeader

- type: startingGear
  id: USMCUniformTeamLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmorFlak
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCGrenadeFilled
    pouchright: FHClothingPouchUSMCAmmoDoubleFilled
    suitstorage: FHWeaponRifleM16A1
    head: FHClothingHeadHelmetM1Woodland
    pocket1: IFAKUSMCFilled

- type: job
  id: USMCMachineGunner
  name: job-name-USMC-machinegunner
  description: job-description-USMC-machinegunner
  playTimeTracker: USMCMachineGunner
  startingGear: USMCUniformMachineGunner
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 6
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCMachineGunner

- type: startingGear
  id: USMCUniformMachineGunner
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackAliceMediumFilledMachineGunner
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCAmmoLMGFilled
    pouchright: FHClothingPouchUSMCAmmoLMGFilled
    suitstorage: FHWeaponLMGM60
    head: FHClothingHeadHelmetM1Net
    pocket1: IFAKUSMCFilled

- type: job
  id: USMCMedic
  name: job-name-USMC-medic
  description: job-description-USMC-medic
  playTimeTracker: USMCMedic
  startingGear: USMCUniformMedic
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 7
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCMedic

- type: startingGear
  id: USMCUniformMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSMCButtPackMedic
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCAmmoFilled
    pouchright: FHClothingPouchUSMCAmmoFilled
    suitstorage: FHWeaponRifleM16A2
    head: FHClothingHeadHelmetM1Medic
    pocket1: IFAKUSMCFilled
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesLatex

- type: job
  id: USMCSniper
  name: job-name-USMC-sniper
  description: job-description-USMC-sniper
  playTimeTracker: USMCSniper
  startingGear: USMCUniformSniper
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 5
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCSniper

- type: startingGear
  id: USMCUniformSniper
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterJacketUSMCParka
    back: FHClothingBackpackUSMCButtPack
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCAmmoFilledSniper
    pouchright: FHClothingPouchUSMCAmmoFilledSniper
    suitstorage: FHWeaponSnipersM21
    head: FHClothingHeadHelmetM1Woodland
    pocket1: IFAKUSMCFilled

- type: job
  id: USMCRTO
  name: job-name-USMC-rto
  description: job-description-USMC-rto
  playTimeTracker: USMCRTO
  startingGear: USMCUniformRTO
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 8
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCRTO

- type: startingGear
  id: USMCUniformRTO
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    back: FHClothingBackRadioANPRC77
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCAmmoFilled
    pouchright: FHClothingPouchUSMCAmmoFilled
    suitstorage: FHWeaponRifleM16A2
    head: FHClothingHeadHelmetM1
    pocket1: IFAKUSMCFilled

- type: job
  id: USMCRifleMan
  name: job-name-USMC-rifleman
  description: job-description-USMC-rifleman
  playTimeTracker: USMCRifleMan
  startingGear: USMCUniformRifleMan
  icon: "Nato"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 4
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskBluFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Nato
        factionName: "United States Marine Corp"

- type: playTimeTracker
  id: USMCRifleMan

- type: startingGear
  id: USMCUniformRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSMCWoodland
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSMCButtPack
    belt: FHClothingBeltUSMCHarness
    pouchleft: FHClothingPouchUSMCAmmoFilled
    pouchright: FHClothingPouchUSMCAmmoFilled
    suitstorage: FHWeaponRifleM16A2
    head: FHClothingHeadHelmetM1
    pocket1: IFAKUSMCFilled
