- type: job
  id: USSRPlatoonLeader
  name: job-name-USSR-platoonleader
  description: job-description-USSR-platoonleader
  playTimeTracker: USSRPlatoonLeader
  startingGear: USSRUniformPlatoonLeader
  icon: "Pact"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 10
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRTeamLeader
  name: job-name-USSR-teamleader
  description: job-description-USSR-teamleader
  playTimeTracker: USSRTeamLeader
  startingGear: USSRUniformTeamLeader
  icon: "Pact"
  whitelisted: true
  joinNotifiyCrew: false
  displayWeight: 9
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRMachineGunner
  name: job-name-USSR-machinegunner
  description: job-description-USSR-machinegunner
  playTimeTracker: USSRMachineGunner
  startingGear: USSRUniformMachineGunner
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 6
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRMedic
  name: job-name-USSR-medic
  description: job-description-USSR-medic
  playTimeTracker: USSRMedic
  startingGear: USSRUniformMedic
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 7
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRRifleMan
  name: job-name-USSR-rifleman
  description: job-description-USSR-rifleman
  playTimeTracker: USSRRifleMan
  startingGear: USSRUniformRifleMan
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 3
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRSniper
  name: job-name-USSR-sniper
  description: job-description-USSR-sniper
  playTimeTracker: USSRSniper
  startingGear: USSRUniformSniper
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 4
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRRTO
  name: job-name-USSR-rto
  description: job-description-USSR-rto
  playTimeTracker: USSRRTO
  startingGear: USSRUniformRTO
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 8
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: job
  id: USSRAutoRifleMan
  name: job-name-USSR-autorifleman
  description: job-description-USSR-autorifleman
  playTimeTracker: USSRAutoRifleMan
  startingGear: USSRUniformAutoRifleMan
  icon: "Pact"
  whitelisted: false
  joinNotifiyCrew: false
  displayWeight: 5
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer
      - type: GameFactionMember
        faction: Warpact
        factionName: "Soviet Army"

- type: playTimeTracker
  id: USSRPlatoonLeader

- type: playTimeTracker
  id: USSRTeamLeader

- type: playTimeTracker
  id: USSRMachineGunner

- type: playTimeTracker
  id: USSRMedic

- type: playTimeTracker
  id: USSRSniper

- type: playTimeTracker
  id: USSRAutoRifleMan

- type: playTimeTracker
  id: USSRRTO

- type: playTimeTracker
  id: USSRRifleMan

- type: startingGear
  id: USSRUniformPlatoonLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmor6b2
    back: FHClothingBackRadioR105D
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRGrenadeFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHatBeretSA
    eyes: ClothingEyesGlassesCheapSunglasses
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformTeamLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmor6b2
    back: FHClothingBackRadioR105D
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRGrenadeFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformMachineGunner
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKitMachineGunnerFilled
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRLMGFilled
    pouchright: FHClothingPouchUSSRLMGFilled
    suitstorage: FHWeaponLMGPKM
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68Medic
    pocket1: IFAKUSSRFilled
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesLatex

- type: startingGear
  id: USSRUniformSniper
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRSVDFilled
    pouchright: FHClothingPouchUSSRSVDFilled
    suitstorage: FHWeaponSnipersSVD
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformAutoRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled45
    pouchright: FHClothingPouchUSSRAmmoFilled45
    suitstorage: FHWeaponLMGRPK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformRTO
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackRadioR105D
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled
