- type: job
  id: USSRPlatoonLeader
  name: job-name-USSR-platoonleader
  description: job-description-USSR-platoonleader
  playTimeTracker: USSRPlatoonLeader
  startingGear: USSRUniformPlatoonLeader
  icon: "USSRPlatoonLeader"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRTeamLeader
  name: job-name-USSR-teamleader
  description: job-description-USSR-teamleader
  playTimeTracker: USSRTeamLeader
  startingGear: USSRUniformTeamLeader
  icon: "USSRTeamLeader"
  whitelisted: true
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRMachineGunner
  name: job-name-USSR-machinegunner
  description: job-description-USSR-machinegunner
  playTimeTracker: USSRMachineGunner
  startingGear: USSRUniformMachineGunner
  icon: "USSRMachineGunner"
  whitelisted: false
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRMedic
  name: job-name-USSR-medic
  description: job-description-USSR-medic
  playTimeTracker: USSRMedic
  startingGear: USSRUniformMedic
  icon: "USSRMedic"
  whitelisted: false
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRRifleMan
  name: job-name-USSR-rifleman
  description: job-description-USSR-rifleman
  playTimeTracker: USSRRifleMan
  startingGear: USSRUniformRifleMan
  icon: "USSRRifleMan"
  whitelisted: false
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRSniper
  name: job-name-USSR-sniper
  description: job-description-USSR-sniper
  playTimeTracker: USSRSniper
  startingGear: USSRUniformSniper
  icon: "USSRRifleMan"
  whitelisted: false
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: job
  id: USSRAutoRifleMan
  name: job-name-USSR-autorifleman
  description: job-description-USSR-autorifleman
  playTimeTracker: USSRAutoRifleMan
  startingGear: USSRUniformAutoRifleMan
  icon: "USSRRifleMan"
  whitelisted: false
  joinNotifiyCrew: false
  special:
  - !type:AddComponentSpecial
    components:
      - type: Fixtures
        fixtures:
          fix1:
            shape:
              !type:PhysShapeCircle
              radius: 0.35
            density: 185
            restitution: 0.0
            mask:
            - MobMaskRedFor
            layer:
            - MobLayer

- type: playTimeTracker
  id: USSRPlatoonLeader

- type: playTimeTracker
  id: USSRTeamLeader

- type: playTimeTracker
  id: USSRMachineGunner

- type: playTimeTracker
  id: USSRMedic

- type: playTimeTracker
  id: USSRSniper

- type: playTimeTracker
  id: USSRAutoRifleMan

- type: playTimeTracker
  id: USSRRifleMan

- type: jobIcon
  parent: JobIcon
  id: USSRPlatoonLeader
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: pact_platoonleader
  jobName: job-name-USSR-platoonleader
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USSRTeamLeader
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: pact_teamleader
  jobName: job-name-USSR-teamleader
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USSRMachineGunner
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: pact_machinegunner
  jobName: job-name-USSR-machinegunner
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USSRMedic
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: pact_medic
  jobName: job-name-USSR-medic
  isCrewJob: false

- type: jobIcon
  parent: JobIcon
  id: USSRRifleMan
  icon:
    sprite: _FinalHorizon/Interface/Misc/job_icons.rsi
    state: pact_rifleman
  jobName: job-name-USSR-rifleman
  isCrewJob: false

- type: startingGear
  id: USSRUniformPlatoonLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmor6b2
    back: FHClothingBackRadioR105D
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRGrenade
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHatBeretSA
    eyes: ClothingEyesGlassesCheapSunglasses
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformTeamLeader
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    outerClothing: FHClothingOuterArmor6b2
    back: FHClothingBackRadioR105D
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRGrenade
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformMachineGunner
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKitMachineGunnerFilled
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRLMGFilled
    pouchright: FHClothingPouchUSSRLMGFilled
    suitstorage: FHWeaponLMGPKM
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68Medic
    pocket1: IFAKUSSRFilled
    mask: ClothingMaskSterile
    gloves: ClothingHandsGlovesLatex

- type: startingGear
  id: USSRUniformSniper
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRSVDFilled
    pouchright: FHClothingPouchUSSRSVDFilled
    suitstorage: FHWeaponSnipersSVD
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformAutoRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled45
    pouchright: FHClothingPouchUSSRAmmoFilled45
    suitstorage: FHWeaponLMGRPK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled

- type: startingGear
  id: USSRUniformRifleMan
  equipment:
    jumpsuit: ClothingUniformJumpsuitUSSRYellow
    shoes: ClothingShoesBootsJack
    back: FHClothingBackpackUSSRKit
    belt: FHClothingBeltUSSRHarness
    pouchleft: FHClothingPouchUSSRAmmoFilled
    pouchright: FHClothingPouchUSSRAmmoFilled
    suitstorage: FHWeaponRifleAK74
    head: FHClothingHeadHelmetSSH68
    pocket1: IFAKUSSRFilled
