- type: entity
  parent: BaseItem
  abstract: true
  id: FHWeaponBase
  components:
  - type: Wieldable
  - type: WieldableDoAfter
    timer: 0.4
  - type: GunWieldBonus
    minAngle: -49
    maxAngle: -35
    angleIncrease: 0
    angleDecay: 0
  - type: Gun
    minAngle: 50
    maxAngle: 50
    angleIncrease: 2.5
    angleDecay: 8
    soundEmpty:
      path: /Audio/_FinalHorizon/Weapons/Guns/Empty/gen_empty.ogg
  - type: SpeedModifiedOnWield
    walkModifier: 0.73
    sprintModifier: 0.73
  - type: PullDoAfter
    pullTime: 0.6
  - type: Scope
    requireWielding: true
    zoomLevels:
    - zoom: 1.4
      offset: 13
      allowMovement: true
      doAfter: 0.1
  - type: FarGunshot
    range: 260
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/ak_dist.ogg

- type: entity
  parent: FHWeaponBase
  abstract: true
  id: FHWeaponBaseLMG
  components:
  - type: WieldableDoAfter
    timer: 1.5
  - type: GunWieldBonus
    minAngle: -48
    maxAngle: -40
  - type: Gun
    angleIncrease: 1
  - type: SpeedModifiedOnWield
    walkModifier: 0.6
    sprintModifier: 0.6
  - type: PullDoAfter
    pullTime: 1
  - type: Scope
    requireWielding: true
    zoomLevels:
    - zoom: 1.6
      offset: 13
      allowMovement: false
      doAfter: 0.2
  - type: FarGunshot
    range: 300
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/mg_dist.ogg

- type: entity
  parent: BaseItem
  id: FHWeaponLauncherBase
  components:
  - type: HeldSpeedModifier
    walkModifier: 0.6
    sprintModifier: 0.6
  - type: PullDoAfter
    pullTime: 2
  - type: Scope
    zoomLevels:
    - zoom: 1.4
      offset: 13
      allowMovement: false
      doAfter: 0.4
  - type: FarGunshot
    range: 190
    sound: /Audio/_FinalHorizon/Weapons/Guns/Far/rpg_dist.ogg
