- type: entity
  parent: BaseItem
  abstract: true
  id: FHWeaponBase
  components:
  - type: Wieldable
  - type: WieldableDoAfter
    timer: 0.4
  - type: GunWieldBonus
    minAngle: -20
    maxAngle: -30
  - type: Gun
    minAngle: 21
    maxAngle: 32
    soundEmpty:
      path: /Audio/_FinalHorizon/Weapons/Guns/Empty/gen_empty.ogg
  - type: SpeedModifiedOnWield
    walkModifier: 0.9
    sprintModifier: 0.9
  - type: PullDoAfter
    pullTime: 0.6
  - type: Scope
    zoomLevels:
    - zoom: 1.6
      offset: 14
      allowMovement: true
      doAfter: 1

- type: entity
  parent: FHWeaponBase
  abstract: true
  id: FHWeaponBaseLMG
  components:
  - type: WieldableDoAfter
    timer: 1
  - type: SpeedModifiedOnWield
    walkModifier: 0.7
    sprintModifier: 0.7
  - type: PullDoAfter
    pullTime: 1

- type: entity
  parent: BaseItem
  id: FHWeaponLauncherBase
  components:
  - type: HeldSpeedModifier
    walkModifier: 0.8
    sprintModifier: 0.8
  - type: PullDoAfter
    pullTime: 2
