- type: entity
  parent: ClothingHeadBase
  id: FHClothingHeadHelmetBase
  abstract: true
  components:
  - type: HideLayerClothing
    layers:
      HeadTop : HEAD
      HeadSide : HEAD
  - type: ExplosionResistance
    damageCoefficient: 0.90 # rework this later

- type: entity
  parent: FHClothingHeadHelmetBase
  id: FHClothingHeadHelmetBaseFoldable
  abstract: true
  components:
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: unfold-verb-clothing-jacket
    foldVerbText: fold-verb-clothing-jacket
  - type: FoldableClothing
    foldedEquippedPrefix: folded
