- type: entity
  parent: ClothingHeadBase
  id: FHClothingHeadHelmetBase
  abstract: true
  components:
  - type: HideLayerClothing
    layers:
      HeadTop : HEAD
      HeadSide : HEAD
  - type: Armor
    modifiers:
      coefficients:
        Piercing: 0.95
  - type: ClothingSpeedModifier
    walkModifier: 0.98
    sprintModifier: 0.98

- type: entity
  parent: FHClothingHeadHelmetBase
  id: FHClothingHeadHelmetBaseFoldable
  abstract: true
  components:
  - type: Foldable
    canFoldInsideContainer: true
    unfoldVerbText: unfold-verb-clothing-jacket
    foldVerbText: fold-verb-clothing-jacket
  - type: FoldableClothing
    foldedEquippedPrefix: folded
