- type: entity
  abstract: true
  parent: Clothing
  id: FHClothingOuterBase
  components:
  - type: Clothing
    slots:
    - outerClothing
  - type: Sprite
    state: icon

- type: entity
  abstract: true
  parent: FHClothingOuterBase
  id: FHClothingOuterArmorBase
  components:
  - type: ExplosionResistance
    damageCoefficient: 0.80
